name: Release GPTWare

on:
    push:
        branches:
            - main
        paths:
            - "gptware.lua"
            - "gptware-orion.lua"
            - "gptware-lt2.lua"

jobs:
    release-main:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'gptware.lua')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get commit ID
              id: get_commit_id
              run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

            - name: Check if main script exists
              id: check_file
              run: |
                  if [ -f "gptware.lua" ]; then
                    echo "Main Script exists"
                    echo "main_script_exists=true" >> $GITHUB_ENV
                  else
                    echo "Main Script does not exist"
                    exit 1
                  fi

            - name: Send data to server
              if: env.main_script_exists == 'true'
              run: |
                  encoded_content=$(base64 -w 0 gptware.lua)
                  echo "Sending POST request with encoded content"
                  curl -X POST https://lncvrt.xyz/api/gptware/update-script \
                    -H "Authorization: ${{ secrets.GPTWARE_KEY }}" \
                    -H "Content-Type: application/json" \
                    -H "Type: main" \
                    -H "Commit: ${{ env.commit_id }}" \
                    -d "{\"content\":\"$encoded_content\"}"

    release-orion:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'gptware-orion.lua')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get commit ID
              id: get_commit_id
              run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

            - name: Check if orion script exists
              id: check_file
              run: |
                  if [ -f "gptware-orion.lua" ]; then
                    echo "Orion Script exists"
                    echo "orion_script_exists=true" >> $GITHUB_ENV
                  else
                    echo "Orion Script does not exist"
                    exit 1
                  fi

            - name: Send data to server
              if: env.orion_script_exists == 'true'
              run: |
                  encoded_content=$(base64 -w 0 gptware-orion.lua)
                  echo "Sending POST request with encoded content"
                  curl -X POST https://lncvrt.xyz/api/gptware/update-script \
                    -H "Authorization: ${{ secrets.GPTWARE_KEY }}" \
                    -H "Content-Type: application/json" \
                    -H "Type: orion" \
                    -H "Commit: ${{ env.commit_id }}" \
                    -d "{\"content\":\"$encoded_content\"}"

    release-lt2:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'gptware-lt2.lua')

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Get commit ID
              id: get_commit_id
              run: echo "commit_id=$(git rev-parse HEAD)" >> $GITHUB_ENV

            - name: Check if LT2 script exists
              id: check_file
              run: |
                  if [ -f "gptware-lt2.lua" ]; then
                    echo "LT2 Script exists"
                    echo "lt2_script_exists=true" >> $GITHUB_ENV
                  else
                    echo "LT2 Script does not exist"
                    exit 1
                  fi

            - name: Send data to server
              if: env.lt2_script_exists == 'true'
              run: |
                  encoded_content=$(base64 -w 0 gptware-lt2.lua)
                  echo "Sending POST request with encoded content"
                  curl -X POST https://lncvrt.xyz/api/gptware/update-script \
                    -H "Authorization: ${{ secrets.GPTWARE_KEY }}" \
                    -H "Content-Type: application/json" \
                    -H "Type: lt2" \
                    -H "Commit: ${{ env.commit_id }}" \
                    -d "{\"content\":\"$encoded_content\"}"
